### ISSUE TITLE
davix stuck in 'bot error' for openssl3 migration

### ISSUE THREAD

**Issue by duncanmmacleod** [regro/cf-scripts#1468]
The [`davix`](https://github.com/conda-forge/davix-feedstock) feedstock is stuck in 'bot error' for the openssl migration with the error message:

```
Traceback (most recent call last):
  File "/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/auto_tick.py", line 1175, in main
    migrator_uid, pr_json = run(
  File "/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/auto_tick.py", line 239, in run
    eval_cmd(
  File "/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/utils.py", line 280, in eval_cmd
   c.check_returncode()
  File "/usr/share/miniconda3/envs/run_env/lib/python3.9/subprocess.py", line 460, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command 'conda smithy rerender -c auto --no-check-uptodate' returned non-zero exit status 1.
```

Getting this unstuck would enable this migration for `root` which would be nice. Happy to help with testing/resolution if I can.

**Comment by duncanmmacleod** [comment]
This migration has been completed (by the bot) for this package.
