### ISSUE TITLE
XGBoost macOS ARM migrator marked as error

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#1890]
The XGBoost feedstock has the macOS ARM migrator applied already. Unfortunately the bot is marking it as having an error. 

<img width="1840" alt="Screenshot 2023-10-17 at 6 37 08 PM" src="https://github.com/regro/cf-scripts/assets/3019665/8f334abc-6c20-4838-a5f3-64105cdcdd09">

We tried clearing the status ( https://github.com/regro/cf-graph-countyfair/pull/8 ), tweaking the recipe ( https://github.com/conda-forge/xgboost-feedstock/pull/140 ), and clearing the status again ( https://github.com/regro/cf-graph-countyfair/pull/9 ). However the bot still marks this as having an error.

While the bot error appears to be related to re-rendering. The same issue does not occur with the re-rendering bot nor with re-rendering locally. Have been unable to reproduce the error seen on the bot

Not sure what we are missing. Raising here in case someone else can spot the issue

**Comment by jakirkham** [comment]
Adding a log snippet from [a recent CI run]( https://github.com/regro/cf-scripts/actions/runs/6580634172/job/17879038573#step:9:3527 ) attempting to apply the macOS ARM migration

<details>

```
Running migrations for OSXArm-arm osx addition: 2
  
  
  2023-10-19 22:17:37,607 INFO     conda_forge_tick.auto_tick || OSXARM-arm osx addition IS MIGRATING xgboost:main
  INFO:Building a url from ('https://api.github.com/', 'rate_limit')
  INFO:JSON was returned
  INFO:Building a url from ('https://api.github.com/', 'repos', 'conda-forge', 'xgboost-feedstock')
  INFO:Missed the cache building the url
  INFO:JSON was returned
  INFO:Building a url from ('https://api.github.com/', 'repos', 'regro-cf-autotick-bot', 'xgboost-feedstock')
  INFO:Missed the cache building the url
  INFO:JSON was returned
  /home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/github/MainClass.py:145: DeprecationWarning: Argument login_or_token is deprecated, please use auth=github.Auth.Token(...) instead
    warnings.warn(
  error: pathspec 'bot-pr_arm_osx_h1124c5' did not match any file(s) known to git
  Cloning into bare repository '/home/runner/micromamba/envs/cf-scripts/conda-bld/git_cache/github.com/dmlc/xgboost'...
  Cloning into '/home/runner/micromamba/envs/cf-scripts/conda-bld/xgboost-split_1697753860072/work'...
  done.
  checkout: 'v1.7.6'
  Note: switching to 'v1.7.6'.
  
  You are in 'detached HEAD' state. You can look around, make experimental
  changes and commit them, and you can discard any commits you make in this
  state without impacting any branches by switching back to a branch.
  
  If you want to create a new branch to retain commits you create, you may
  do so (now or later) by using -c with the switch command. Example:
  
    git switch -c <new-branch-name>
  
  Or undo this operation with:
  
    git switch -
  
  Turn off this advice by setting config variable advice.detachedHead to false
  
  HEAD is now at 36eb41c96 Bump version to 1.7.6 (#9305)
  Submodule 'cub' (https://github.com/NVlabs/cub) registered for path 'cub'
  Submodule 'dmlc-core' (https://github.com/dmlc/dmlc-core) registered for path 'dmlc-core'
  Submodule 'gputreeshap' (https://github.com/rapidsai/gputreeshap.git) registered for path 'gputreeshap'
  Cloning into '/home/runner/micromamba/envs/cf-scripts/conda-bld/xgboost-split_1697753860072/work/cub'...
  Cloning into '/home/runner/micromamba/envs/cf-scripts/conda-bld/xgboost-split_1697753860072/work/dmlc-core'...
  Cloning into '/home/runner/micromamba/envs/cf-scripts/conda-bld/xgboost-split_1697753860072/work/gputreeshap'...
  Submodule path 'cub': checked out 'af39ee264f4627608072bf54730bf3a862e56875'
  Submodule path 'dmlc-core': checked out '81db539486ce6525b31b971545edffee2754aced'
  Submodule path 'gputreeshap': checked out '787259b412c18ab8d5f24bf2b8bd6a59ff8208f3'
  ==> /home/runner/micromamba/envs/cf-scripts/bin/git log -n1 <==
  
  commit 36eb41c960483c8b52b44082663c99e6a0de440a
  Author: Jiaming Yuan <jm.yuan@outlook.com>
  Date:   Fri Jun 16 03:33:16 2023 +0800
  
      Bump version to 1.7.6 (#9305)
  
  ==> /home/runner/micromamba/envs/cf-scripts/bin/git describe --tags --dirty <==
  
  v1.7.6
  
  ==> /home/runner/micromamba/envs/cf-scripts/bin/git status <==
  
  HEAD detached at v1.7.6
  nothing to commit, working tree clean
  
  Applying patch: /home/runner/work/cf-scripts/cf-scripts/cf-graph/feedstocks/xgboost-feedstock/recipe/0001-conda-Unbundle-libxgboost.-dll-dylib-so.patch
  Applying patch: /home/runner/work/cf-scripts/cf-scripts/cf-graph/feedstocks/xgboost-feedstock/recipe/0001-conda-Unbundle-libxgboost.-dll-dylib-so.patch with args:
  ['-Np1', '-i', '/tmp/tmpxet04v2f/0001-conda-Unbundle-libxgboost.-dll-dylib-so.patch.native', '--binary']
  checking file python-package/xgboost/libpath.py
  patching file python-package/xgboost/libpath.py
  Patch analysis gives:
  [[ RA-MD1LOVE ]] - [[                      0001-conda-Unbundle-libxgboost.-dll-dylib-so.patch ]]
  
  Key:
  
  R :: Reversible                       A :: Applicable
  Y :: Build-prefix patch in use        M :: Minimal, non-amalgamated
  D :: Dry-runnable                     N :: Patch level (1 is preferred)
  L :: Patch level not-ambiguous        O :: Patch applies without offsets
  V :: Patch applies without fuzz       E :: Patch applies without emitting to stderr
  
  2023-10-19 22:17:59,555 INFO     conda_forge_tick.auto_tick || Rerendering the feedstock
  INFO:conda_smithy.configure_feedstock:__pycache__ rendering is skipped
  INFO:conda_smithy.configure_feedstock:README rendering is skipped
  INFO:conda_smithy.configure_feedstock:python312.yaml from feedstock is ignored and upstream version is used
  INFO:conda_smithy.configure_feedstock:cuda120.yaml from feedstock is ignored and upstream version is used
  INFO:conda_smithy.configure_feedstock:cuda118.yaml from feedstock is ignored and upstream version is used
  WARNING: Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
  WARNING: Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
  WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.22
  INFO:conda_smithy.configure_feedstock:Applying migrations: /home/runner/.cache/conda-smithy/share/conda-forge/migrations/cuda120.yaml,/home/runner/.cache/conda-smithy/share/conda-forge/migrations/cuda118.yaml,/home/runner/.cache/conda-smithy/share/conda-forge/migrations/python312.yaml
  Problematic recipe:
  
  
  
  
  package:
    name: xgboost-split
    version: 1.7.6
  
  source:
    git_url: https://github.com/dmlc/xgboost
    git_tag: v1.7.6
    patches:
      - 0001-conda-Unbundle-libxgboost.-dll-dylib-so.patch
  
  build:
    number: 5
  
  requirements:
    build:
      - python
      - cross-python_
      - cross-r-base
      - r-knitr
      - r-jsonlite
      - r-magrittr
      - r-matrix
      - r-data.table
      - gcc_linux-64
      - gxx_linux-64
      - cuda_linux-64
      - git
      - cmake
      - libgomp
      - ninja
    host:
      - nccl
  
  outputs:
    - name: libxgboost
      script: install-libxgboost.sh
      build:
        activate_in_script: True
        string: cudah1234567_0
        ignore_run_exports_from:
      requirements:
        build:
          - cross-r-base
          - r-knitr
          - r-jsonlite
          - r-magrittr
          - r-matrix
          - r-data.table
          - gcc_linux-64
          - gxx_linux-64
          - cuda_linux-64
          - git
          - cmake
          - make
          - libgomp
        host:
          - nccl
        run:
          - __cuda
  
  
    - name: _py-xgboost-mutex
      version: 2.0
      build:
        string: gpu_0
  
    - name: py-xgboost
      script: install-py-xgboost.sh
      build:
        string: cudapy310h1234567_0
      requirements:
        build:
          - cross-r-base
          - r-knitr
          - r-jsonlite
          - r-magrittr
          - r-matrix
          - r-data.table
          - python
          - cross-python_
        host:
          - libxgboost
          - python
          - setuptools
          - pip
        run:
          - libxgboost
          - _py-xgboost-mutex
          - python
          - numpy
          - scipy
          - scikit-learn
          - __cuda
      test:
        script: test-py-xgboost.py
        imports:
          - xgboost
  
    - name: py-xgboost-cpu
      build:
        skip: true
      requirements:
        host:
          - python
          - py-xgboost
        run:
          - python
          - py-xgboost
  
    - name: py-xgboost-gpu
      build:
        - cross-r-base
        - r-knitr
        - r-jsonlite
        - r-magrittr
        - r-matrix
        - r-data.table
      requirements:
        host:
          - python
          - py-xgboost
        run:
          - python
          - py-xgboost
          - __cuda
  
  
    - name: xgboost
      build:
        - cross-r-base
        - r-knitr
        - r-jsonlite
        - r-magrittr
        - r-matrix
        - r-data.table
        string: cudapy310h1234567_0
      requirements:
        host:
          - python
        run:
          - python
          - py-xgboost
          - __cuda
  
    - name: _r-xgboost-mutex
      version: 2.0
      build:
        - cross-r-base
        - r-knitr
        - r-jsonlite
        - r-magrittr
        - r-matrix
        - r-data.table
        string: gpu_0
  
    - name: r-xgboost
      script: install-r-xgboost.sh
      build:
        string: cuda_rh1234567_0
        rpaths:
          - lib/R/lib
      requirements:
        build:
          - cross-r-base
          - r-knitr
          - r-jsonlite
          - r-magrittr
          - r-matrix
          - r-data.table
          - gcc_linux-64
          - gxx_linux-64
          - libgomp
          - git
          - make
          - cmake
          - ninja
          - cross-r-base
          - r-base
          - r-matrix
          - r-data.table
          - r-magrittr
          - r-jsonlite
          - r-knitr
        host:
          - libxgboost
          - r-base
          - r-matrix
          - r-data.table
          - r-magrittr
          - r-jsonlite
          - r-knitr
        run:
          - libxgboost
          - _r-xgboost-mutex
          - r-base
          - r-matrix
          - r-data.table
          - r-magrittr
          - r-jsonlite
          - __cuda
      test:
        files:
          - test-r-xgboost.r
        commands:
          - Rscript test-r-xgboost.r
  
    - name: r-xgboost-cpu
      build:
        skip: true
      requirements:
        host:
          - r-base
        run:
          - r-base
          - r-xgboost
  
    - name: r-xgboost-gpu
      build:
        - cross-r-base
        - r-knitr
        - r-jsonlite
        - r-magrittr
        - r-matrix
        - r-data.table
      requirements:
        host:
          - r-base
        run:
          - r-base
          - r-xgboost
          - __cuda
  
  about:
    home: https://github.com/dmlc/xgboost
    license: Apache-2.0
    license_file: LICENSE
    summary: |
      Scalable, Portable and Distributed Gradient Boosting (GBDT, GBRT or GBM) Library, for
      Python, R, Java, Scala, C++ and more. Runs on single machine, Hadoop, Spark, Flink
      and DataFlow
    description: |
      XGBoost is an optimized distributed gradient boosting library designed to be highly efficient,
      flexible and portable. It implements machine learning algorithms under the Gradient Boosting
      framework. XGBoost provides a parallel tree boosting (also known as GBDT, GBM) that solve many
      data science problems in a fast and accurate way. The same code runs on major distributed
      environment (Hadoop, SGE, MPI) and can solve problems beyond billions of examples.
    doc_url: https://xgboost.readthedocs.io/
    dev_url: https://github.com/dmlc/xgboost/
  
  extra:
    feedstock-name: xgboost
    recipe-maintainers:
      - aldanor
      - fhoehle
      - jakirkham
      - ksangeek
      - xhochy
      - mfansler
  
  ----------------------------------------------------------------------
  Unable to parse meta.yaml file
  
  Error Message:
  --> while parsing a block collection
  -->   in "<unicode string>", line 134, column 7
  --> did not find expected '-' indicator
  -->   in "<unicode string>", line 140, column 7
  
  Adding in variants from internal_defaults
  Adding in variants from /home/runner/.cache/conda-smithy/conda_build_config.yaml
  
  RERENDER ERROR: Command 'conda smithy rerender -c auto --no-check-uptodate' returned non-zero exit status 1.
  2023-10-19 22:18:00,962 ERROR    conda_forge_tick.auto_tick || NON GITHUB ERROR
  Traceback (most recent call last):
    File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py", line 1270, in _run_migrator
      migrator_uid, pr_json = run(
    File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py", line 292, in run
      eval_cmd(
    File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/os_utils.py", line 36, in eval_cmd
      c.check_returncode()
    File "/home/runner/micromamba/envs/cf-scripts/lib/python3.10/subprocess.py", line 457, in check_returncode
      raise CalledProcessError(self.returncode, self.args, self.stdout,
  subprocess.CalledProcessError: Command 'conda smithy rerender -c auto --no-check-uptodate' returned non-zero exit status 1.
  2023-10-19 22:18:04,010 INFO     conda_forge_tick.auto_tick || /home/runner/work/cf-scripts/cf-scripts/cf-graph
  INFO:Building a url from ('https://api.github.com/', 'rate_limit')
```

</details>

**Comment by beckermr** [comment]
So the r mutex output is not being rendered properly. The bot doesn't use exactly the same rendering recipe as smithy.

**Comment by jakirkham** [comment]
Thanks Matt! 🙏

Yeah was wondering how bot parsing is done

Noticed the top-level `build` for each output has `requirements/build` info put in it (sometimes not even the `requirements/build` from that package). Wonder if it has something to do with how the `build` section is constructed in some of these `outputs`

Would having selectors on `build/string`s be confusing to the bot? If so, maybe we could change that with something like PR ( https://github.com/conda-forge/xgboost-feedstock/pull/143 )

**Comment by beckermr** [comment]
Yes selectors and jinja2 mixing causes issues.

**Comment by beckermr** [comment]
I wonder if this is a minimigrator that is messing things up. The best way to test would be to add a test to the bot test suite and see what happens. I'd use a version migrator with all of the minimigrators attached to generate the error, and then remove them one by one until the error goes away,

**Comment by jakirkham** [comment]
At some point we managed to clear this. Unfortunately have lost track of what exactly was needed at this point. In any event closing as resolved
