### ISSUE TITLE
pagmo failing for stdlib minimigrator

### ISSUE THREAD

**Issue by beckermr** [regro/cf-scripts#2322]
See this error:

```
2024-03-26T12:30:54.8385477Z error: pathspec 'rebuild-boost1840-0-1_h142599' did not match any file(s) known to git
2024-03-26T12:30:54.8445365Z 2024-03-26 12:30:54,843 ERROR    conda_forge_tick.auto_tick || NON GITHUB ERROR
2024-03-26T12:30:54.8446237Z Traceback (most recent call last):
2024-03-26T12:30:54.8447704Z   File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py", line 1273, in _run_migrator
2024-03-26T12:30:54.8449196Z     migrator_uid, pr_json = run(
2024-03-26T12:30:54.8449817Z                             ^^^^
2024-03-26T12:30:54.8451245Z   File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py", line 243, in run
2024-03-26T12:30:54.8452354Z     migrator.run_pre_piggyback_migrations(recipe_dir, feedstock_ctx.attrs, **kwargs)
2024-03-26T12:30:54.8453693Z   File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/migrators/core.py", line 262, in run_pre_piggyback_migrations
2024-03-26T12:30:54.8454728Z     mini_migrator.migrate(recipe_dir, attrs, **kwargs)
2024-03-26T12:30:54.8455760Z   File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/migrators/cstdlib.py", line 210, in migrate
2024-03-26T12:30:54.8456673Z     chunk, cbc = _process_section(name, attrs, section)
2024-03-26T12:30:54.8457157Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-26T12:30:54.8457957Z   File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/migrators/cstdlib.py", line 158, in _process_section
2024-03-26T12:30:54.8458825Z     raise RuntimeError("Don't know where to insert build section!")
```

from this bot job: https://github.com/regro/cf-scripts/actions/runs/8435168649/job/23099982258

cc @h-vetinari

**Comment by h-vetinari** [comment]
Fixed by #2327
