### ISSUE TITLE
Improvements to bot error reporting

### ISSUE THREAD

**Issue by h-vetinari** [regro/cf-scripts#2640]
With the new docker encapsulation, we're getting stacktraces etc. that are much harder to read. Example below the fold:

<details>

```
Traceback (most recent call last):
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py", line 567, in _run_migrator_on_feedstock_branch
    migrator_uid, pr_json = run(
                            ^^^^
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py", line 259, in run
    rerender_msg = rerender_feedstock(feedstock_dir, timeout=900)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/rerender_feedstock.py", line 49, in rerender_feedstock
    return rerender_feedstock_containerized(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/rerender_feedstock.py", line 102, in rerender_feedstock_containerized
    data = run_container_task(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py", line 249, in run_container_task
    raise RuntimeError(
RuntimeError: Error running rerender-feedstock in container - error RuntimeError('Failed to rerender.\noutput: Traceback (most recent call last):\n  File "/opt/conda/envs/cf-scripts/bin/conda-smithy", line 10, in \n    sys.exit(main())\n             ^^^^^^\n  File "/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py", line 737, in main\n    args.subcommand_func(args)\n  File "/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py", line 586, in __call__\n    self._call(args, args.temporary_directory)\n  File "/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py", line 589, in _call\n    configure_feedstock.main(\n  File "/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py", line 2714, in main\n    exclusive_config_file, cf_pinning_ver = get_cached_cfp_file_path(\n                                            ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py", line 2528, in get_cached_cfp_file_path\n    current_pinning_version = get_most_recent_version(\n                              ^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py", line 2398, in get_most_recent_version\n    request.raise_for_status()\n  File "/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 524 Server Error:  for url: https://api.anaconda.org/package/conda-forge/conda-forge-pinning\n\n') raised:
cmd: ['docker',
 'run',
 '-e',
 'CF_TICK_IN_CONTAINER=true',
 '--security-opt=no-new-privileges',
 '--read-only',
 '--cap-drop=all',
 '--mount',
 'type=tmpfs,destination=/tmp,tmpfs-mode=1777,tmpfs-size=6000000000',
 '-m',
 '6000m',
 '--cpus',
 '1',
 '--ulimit',
 'nofile=1024:1024',
 '--ulimit',
 'nproc=2048:2048',
 '--rm',
 '-i',
 '--mount',
 'type=bind,source=/tmp/tmpf55w0b8p,destination=/cf_tick_dir',
 'ghcr.io/regro/conda-forge-tick:master',
 '/opt/conda/envs/cf-scripts/bin/python',
 '-u',
 '/opt/autotick-bot/docker/run_bot_task.py',
 'rerender-feedstock',
 '--timeout',
 '900',
 '--log-level',
 'info']
stdout: {'data': None,
 'error': "RuntimeError('Failed to rerender.\\noutput: Traceback (most recent "
          'call last):\\n  File "/opt/conda/envs/cf-scripts/bin/conda-smithy", '
          'line 10, in \\n    sys.exit(main())\\n             '
          '^^^^^^\\n  File '
          '"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py", '
          'line 737, in main\\n    args.subcommand_func(args)\\n  File '
          '"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py", '
          'line 586, in __call__\\n    self._call(args, '
          'args.temporary_directory)\\n  File '
          '"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py", '
          'line 589, in _call\\n    configure_feedstock.main(\\n  File '
          '"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py", '
          'line 2714, in main\\n    exclusive_config_file, cf_pinning_ver = '
          'get_cached_cfp_file_path(\\n                                            '
          '^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File '
          '"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py", '
          'line 2528, in get_cached_cfp_file_path\\n    '
          'current_pinning_version = '
          'get_most_recent_version(\\n                              '
          '^^^^^^^^^^^^^^^^^^^^^^^^\\n  File '
          '"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py", '
          'line 2398, in get_most_recent_version\\n    '
          'request.raise_for_status()\\n  File '
          '"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/requests/models.py", '
          'line 1021, in raise_for_status\\n    raise '
          'HTTPError(http_error_msg, '
          'response=self)\\nrequests.exceptions.HTTPError: 524 Server Error:  '
          'for url: '
          "https://api.anaconda.org/package/conda-forge/conda-forge-pinning\\n\\n')",
 'timeout': 900,
 'traceback': 'Traceback (most recent call last):\n'
              '  File "/opt/autotick-bot/docker/run_bot_task.py", line 118, in '
              '_run_bot_task\n'
              '    data = func(**kwargs)\n'
              '           ^^^^^^^^^^^^^^\n'
              '  File "/opt/autotick-bot/docker/run_bot_task.py", line 239, in '
              '_rerender_feedstock\n'
              '    msg = rerender_feedstock_local(fs_dir, **kwargs)\n'
              '          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n'
              '  File '
              '"/opt/autotick-bot/conda_forge_tick/rerender_feedstock.py", '
              'line 239, in rerender_feedstock_local\n'
              '    raise RuntimeError(f"Failed to rerender.\\noutput: '
              '{ret.stdout}\\n")\n'
              'RuntimeError: Failed to rerender.\n'
              'output: Traceback (most recent call last):\n'
              '  File "/opt/conda/envs/cf-scripts/bin/conda-smithy", line 10, '
              'in \n'
              '    sys.exit(main())\n'
              '             ^^^^^^\n'
              '  File '
              '"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py", '
              'line 737, in main\n'
              '    args.subcommand_func(args)\n'
              '  File '
              '"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py", '
              'line 586, in __call__\n'
              '    self._call(args, args.temporary_directory)\n'
              '  File '
              '"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py", '
              'line 589, in _call\n'
              '    configure_feedstock.main(\n'
              '  File '
              '"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py", '
              'line 2714, in main\n'
              '    exclusive_config_file, cf_pinning_ver = '
              'get_cached_cfp_file_path(\n'
              '                                            '
              '^^^^^^^^^^^^^^^^^^^^^^^^^\n'
              '  File '
              '"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py", '
              'line 2528, in get_cached_cfp_file_path\n'
              '    current_pinning_version = get_most_recent_version(\n'
              '                              ^^^^^^^^^^^^^^^^^^^^^^^^\n'
              '  File '
              '"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py", '
              'line 2398, in get_most_recent_version\n'
              '    request.raise_for_status()\n'
              '  File '
              '"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/requests/models.py", '
              'line 1021, in raise_for_status\n'
              '    raise HTTPError(http_error_msg, response=self)\n'
              'requests.exceptions.HTTPError: 524 Server Error:  for url: '
              'https://api.anaconda.org/package/conda-forge/conda-forge-pinning\n'
              '\n'
              '\n'}
```

</details>

I think we should catch those errors and `"".join()` the error and the traceback, before displaying it.

Also note the HTTP failure in `get_most_recent_version` - we should probably add an auto-retry in smithy for that.

**Comment by beckermr** [comment]
@h-vetinari has this gotten better for you to the point that we can close this one?

**Comment by h-vetinari** [comment]
I think so yes, so let's close. If another problem comes up I'll open another issue. Thanks for all the work on this!
