### ISSUE TITLE
Logging error

### ISSUE THREAD

**Issue by justcalamari** [regro/cf-scripts#266]
```
--- Logging error ---
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/opt/conda/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/opt/conda/lib/python3.6/logging/__init__.py", line 578, in format
    s = self.formatMessage(record)
  File "/opt/conda/lib/python3.6/logging/__init__.py", line 547, in formatMessage
    return self._style.format(record)
  File "/opt/conda/lib/python3.6/logging/__init__.py", line 391, in format
    return self._fmt % record.__dict__
ValueError: unsupported format character '|' (0x7c) at index 37
Call stack:
  File "/opt/conda/bin/conda-forge-tick", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/root/repo/cf-scripts/scripts/conda-forge-tick", line 3, in <module>
    main()
  File "/root/repo/cf-scripts/conda_forge_tick/cli.xsh", line 21, in main
    int_script_dict[script]()
  File "/root/repo/cf-scripts/conda_forge_tick/update_upstream_versions.py", line 249, in main
    logger.info("Reading graph")
Message: 'Reading graph'
Arguments: ()
```

**Comment by justcalamari** [comment]
@mariusvniekerk

**Comment by CJ-Wright** [comment]
also https://circleci.com/gh/regro/circle_worker/191
```python
--- Logging error ---
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/opt/conda/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/opt/conda/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/opt/conda/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/opt/conda/bin/conda-forge-tick", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/root/repo/cf-scripts/scripts/conda-forge-tick", line 3, in <module>
    main()
  File "/root/repo/cf-scripts/conda_forge_tick/cli.xsh", line 21, in main
    int_script_dict[script]()
  File "/root/repo/cf-scripts/conda_forge_tick/auto_tick.xsh", line 158, in main
    $PROJECT)
```
