### ISSUE TITLE
conda error

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#272]
```python
class: CondaValueError
message:
Malformed version string 'CMIP6_CVs.6.2.8.23%2FDREQ.01.00.24%2FCMOR.3.3.3': invalid character(s).
kwargs:
{}

class: CondaValueError
message:
Malformed version string 'CMIP6_CVs.6.2.8.23%2FDREQ.01.00.24%2FCMOR.3.3.3': invalid character(s).
kwargs:
{}

concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/root/repo/cf-scripts/conda_forge_tick/update_upstream_versions.py", line 195, in get_latest_version
    ver = source.get_version(url)
  File "/root/repo/cf-scripts/conda_forge_tick/update_upstream_versions.py", line 67, in get_version
    return max(vers, key=lambda x: VersionOrder(x.replace("-", ".")))
  File "/root/repo/cf-scripts/conda_forge_tick/update_upstream_versions.py", line 67, in <lambda>
    return max(vers, key=lambda x: VersionOrder(x.replace("-", ".")))
  File "/opt/conda/lib/python3.6/site-packages/conda/models/version.py", line 163, in __new__
    raise CondaValueError(message + "invalid character(s).")
conda.exceptions.CondaValueError: <unprintable CondaValueError object>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/repo/cf-scripts/conda_forge_tick/update_upstream_versions.py", line 218, in update_upstream_versions
    attrs['new_version'] = f.result()
  File "/opt/conda/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
conda.exceptions.CondaValueErrorclass: CondaValueError
message:
Malformed version string 'CMIP6_CVs.6.2.8.23%2FDREQ.01.00.24%2FCMOR.3.3.3': invalid character(s).
kwargs:
{}

: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/conda-forge-tick", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/root/repo/cf-scripts/scripts/conda-forge-tick", line 3, in <module>
    main()
  File "/root/repo/cf-scripts/conda_forge_tick/cli.xsh", line 21, in main
    int_script_dict[script]()
  File "/root/repo/cf-scripts/conda_forge_tick/update_upstream_versions.py", line 252, in main
    update_upstream_versions(gx)
  File "/root/repo/cf-scripts/conda_forge_tick/update_upstream_versions.py", line 221, in update_upstream_versions
    "Error getting uptream version of {}: {}".format(node, e))
  File "/opt/conda/lib/python3.6/site-packages/conda/__init__.py", line 48, in __str__
    return text_type(self.message % self._kwargs)
TypeError: must be real number, not dict
Exited with code 1
```

**Comment by CJ-Wright** [comment]
This looks like a real conda thing 
xref: https://github.com/conda/conda/issues/7532
