### ISSUE TITLE
more github backend errors

### ISSUE THREAD

**Issue by beckermr** [regro/cf-scripts#2902]
Now I am seeing: 

```
fatal: 'upstream/20.x' is not a commit and a branch '20.x' cannot be created from it
```

**Comment by beckermr** [comment]
This is for making PRs against non-default upstream branches

```
  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  > ARCHREBUILD-aarch64 and ppc64le addition IS MIGRATING nodejs:20.x
  fatal: 'upstream/20.x' is not a commit and a branch '20.x' cannot be created from it
  fatal: 'upstream/20.x' is not a commit and a branch '20.x' cannot be created from it
  2024-08-02 16:10:43,030 ERROR    conda_forge_tick.auto_tick || NON GITHUB ERROR
  Traceback (most recent call last):
    File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py", line 165, in _run_git_command
      return subprocess.run(
             ^^^^^^^^^^^^^^^
    File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/subprocess.py", line 571, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['git', 'checkout', '--quiet', '--track', 'upstream/20.x']' returned non-zero exit status 128.
  The above exception was the direct cause of the following exception:
  Traceback (most recent call last):
    File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py", line 351, in clone_fork_and_branch
      self.checkout_branch(target_dir, f"upstream/{base_branch}", track=True)
    File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/contextlib.py", line 81, in inner
      return func(*args, **kwds)
             ^^^^^^^^^^^^^^^^^^^
    File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py", line 273, in checkout_branch
      self._run_git_command(
    File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/contextlib.py", line 81, in inner
      return func(*args, **kwds)
             ^^^^^^^^^^^^^^^^^^^
    File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py", line 169, in _run_git_command
      raise GitCliError("Error running git command.") from e
  conda_forge_tick.git_utils.GitCliError: Error running git command.
  During handling of the above exception, another exception occurred:
  Traceback (most recent call last):
    File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py", line 165, in _run_git_command
      return subprocess.run(
             ^^^^^^^^^^^^^^^
    File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/subprocess.py", line 571, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['git', 'checkout', '--quiet', '-b', '20.x', 'upstream/20.x']' returned non-zero exit status 128.
  The above exception was the direct cause of the following exception:
  Traceback (most recent call last):
    File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py", line 567, in _run_migrator_on_feedstock_branch
      migrator_uid, pr_json = run(
                              ^^^^
    File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py", line 197, in run
      feedstock_dir, repo = get_repo(
                            ^^^^^^^^^
    File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/contextlib.py", line 81, in inner
      return func(*args, **kwds)
             ^^^^^^^^^^^^^^^^^^^
    File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py", line 762, in get_repo
      backend.clone_fork_and_branch(
    File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/contextlib.py", line 81, in inner
      return func(*args, **kwds)
             ^^^^^^^^^^^^^^^^^^^
    File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py", line 461, in clone_fork_and_branch
      self.cli.clone_fork_and_branch(
    File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/contextlib.py", line 81, in inner
      return func(*args, **kwds)
             ^^^^^^^^^^^^^^^^^^^
    File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py", line 359, in clone_fork_and_branch
      self.checkout_new_branch(
    File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/contextlib.py", line 81, in inner
      return func(*args, **kwds)
             ^^^^^^^^^^^^^^^^^^^
    File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py", line 291, in checkout_new_branch
      self._run_git_command(
    File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/contextlib.py", line 81, in inner
      return func(*args, **kwds)
             ^^^^^^^^^^^^^^^^^^^
    File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py", line 169, in _run_git_command
      raise GitCliError("Error running git command.") from e
  conda_forge_tick.git_utils.GitCliError: Error running git command.
```

**Comment by beckermr** [comment]
xref: https://github.com/conda-forge/nodejs-feedstock/issues/363
