### ISSUE TITLE
Many migration feedstocks failing to be rerendered with `GitCliError`

### ISSUE THREAD

**Issue by h-vetinari** [regro/cf-scripts#3023]
Continuation of https://github.com/conda-forge/conda-forge-feedstock-ops/issues/23. Latest protobuf [migrator](https://conda-forge.org/status/migration/?name=libgrpc167_libprotobuf5282) PRs (and probably many others) all have a new error now, still no successfully opened PRs. Here's one example ([logs](https://github.com/regro/cf-scripts/actions/runs/11417860282)):

<details>

```
Traceback (most recent call last):
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py", line 202, in _run_git_command
    p = subprocess.run(
        ^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'push', 'https://github.com/regro-cf-autotick-bot/pytorch-cpu-feedstock.git', 'rebuild-libgrpc167_libprotobuf5282-0-1_hcc6ed3']' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py", line 720, in _run_migrator_on_feedstock_branch
    migrator_uid, pr_json = run_with_tmpdir(
                            ^^^^^^^^^^^^^^^^
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py", line 451, in run_with_tmpdir
    return run(
           ^^^^
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py", line 575, in run
    git_backend.push_to_repository(
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py", line 831, in push_to_repository
    self.cli.push_to_url(git_dir, remote_url, branch)
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py", line 295, in push_to_url
    self._run_git_command(["push", remote_url, branch], git_dir)
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py", line 214, in _run_git_command
    raise GitCliError(f"Error running git command: {repr(e)}")
conda_forge_tick.git_utils.GitCliError: Error running git command: CalledProcessError(128, ['git', 'push', 'https://github.com/regro-cf-autotick-bot/pytorch-cpu-feedstock.git', 'rebuild-libgrpc167_libprotobuf5282-0-1_hcc6ed3'])
```

</details>

**Comment by ytausch** [comment]
Likely related to #3004

**Comment by ytausch** [comment]
The relevant line is this here:

```
2024-10-19T14:13:04.5717175Z fatal: unable to access 'https://github.com/regro-cf-autotick-bot/pytorch-cpu-feedstock.git/': The requested URL returned error: 400
```

**Comment by ytausch** [comment]
Unfortunately, problems like this can happen because #261 is not yet finished.

@beckermr let's revert my changes for now?

**Comment by h-vetinari** [comment]
Thanks for fixing this, even if it meant a revert. 🙏
