### ISSUE TITLE
Missing compiler rebuild PR for metis

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#386]
AFAICT `metis` has no blocking dependencies, yet there is no compiler rebuild PR. Any ideas why?

xref: https://github.com/conda-forge/metis-feedstock/issues/17

**Comment by CJ-Wright** [comment]
Most likely it is waiting on `cmake`.

**Comment by jakirkham** [comment]
`cmake` is done. ( https://github.com/conda-forge/cmake-feedstock/pull/72 ) Other ideas?

**Comment by CJ-Wright** [comment]
There is a traceback
```python
Traceback (most recent call last):
  File "/root/repo/cf-scripts/conda_forge_tick/auto_tick.xsh", line 313, in main
    hash_type=attrs.get('hash_type', 'sha256'))
  File "/root/repo/cf-scripts/conda_forge_tick/auto_tick.xsh", line 72, in run
    gh=gh)
  File "/root/repo/cf-scripts/conda_forge_tick/git_utils.xsh", line 133, in get_repo
    git pull @(upstream) master
  File "/opt/conda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 21217, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured="hiddenobject")
  File "/opt/conda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 21180, in run_subproc
    command.end()
  File "/opt/conda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 13815, in end
    self._end(tee_output=tee_output)
  File "/opt/conda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 13834, in _end
    self._raise_subproc_error()
  File "/opt/conda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 13961, in _raise_subproc_error
    raise subprocess.CalledProcessError(rtn, spec.cmd, output=self.output)
subprocess.CalledProcessError: Command '['/usr/bin/git', 'pull', 'https://github.com/conda-forge/metis-feedstock.git', 'master']' returned non-zero exit status 1.
```

So there seems like there was a problem with `git pull`?

**Comment by CJ-Wright** [comment]
Maybe we should update the bot's master first?

**Comment by jakirkham** [comment]
Sounds reasonable.

**Comment by CJ-Wright** [comment]
@regro/auto-tick thoughts on how to do this nicely?

**Comment by CJ-Wright** [comment]
I don't know exactly myself. Here is the code https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/git_utils.xsh#L127

**Comment by CJ-Wright** [comment]
Its the same. I think we will need to reset hard our master on upstream. @scopatz thoughts?

**Comment by SylvainCorlay** [comment]
Now metis appears in `awaiting-parents` section, while it was not showing at all before.

**Comment by jakirkham** [comment]
Guess that is an improvement, but not sure why it thinks it is missing dependencies. It only needs `cmake` to build, which is already available.

**Comment by jakirkham** [comment]
Would be curious to know what the underlying problem ended up being.

**Comment by CJ-Wright** [comment]
We now hard reset onto upstream master for the bot, there were some lingering files which were stored in the bot's master which were causing pulls from upstream master to fail (even when we told git to use theirs as the merge strategy)
