### ISSUE TITLE
tickbot deploy broken by #709

### ISSUE THREAD

**Issue by duncanmmacleod** [regro/cf-scripts#712]
The PR #709 (specifically 2c77a8ff7bdbacdfcb7d0b72801c73741b266d87) broke the tick bot for non-dry-run operation, see [here](https://app.circleci.com/jobs/github/regro/circle_worker/12753):

```pytb
Traceback (most recent call last):
  File "/opt/conda/envs/run_env/bin/conda-forge-tick", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/root/repo/cf-scripts/scripts/conda-forge-tick", line 5, in <module>
    main()
  File "/root/repo/cf-scripts/conda_forge_tick/cli.xsh", line 54, in main
    int_script_dict[script](args)
TypeError: deploy() takes 0 positional arguments but 1 was given
```

Presumably something like this is needed:

```patch
diff --git a/conda_forge_tick/cli.xsh b/conda_forge_tick/cli.xsh
index 9c2ca04..5165216 100644
--- a/conda_forge_tick/cli.xsh
+++ b/conda_forge_tick/cli.xsh
@@ -10,7 +10,7 @@ from .auto_tick import main as main_auto_tick
 from .status_report import main as main_status_report


-def deploy():
+def deploy(args=None):
     """Deploy the graph to github"""
     for cmd in [['git', 'add', 'pr_json/*'],
                 ['git', 'add', 'status/*'],
```

If this looks correct, I'm happy to migrate this into a PR.

**Comment by CJ-Wright** [comment]
A PR would be great!
