### ISSUE TITLE
Error with dowload_samples

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#79]
```python
(dp_dev) christopher@christopher-ubuntu ~/test_sampledb $ download_samples test.xlsx
Traceback (most recent call last):
  File "/home/christopher/mc/envs/dp_dev/bin/download_samples", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/christopher/dev/sampledb-1/scripts/download_samples", line 3, in <module>
    download_samples()
  File "/home/christopher/dev/sampledb-1/sampledb/reader.xsh", line 192, in download_samples
    args.collection, args.key, args.user, args.port)
  File "/home/christopher/dev/sampledb-1/sampledb/reader.xsh", line 142, in download_sample_spreadsheet
    download(filename, sdb)
  File "/home/christopher/dev/sampledb-1/sampledb/reader.xsh", line 123, in download
    schema = json.loads(schema)
  File "/home/christopher/mc/envs/dp_dev/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

**Comment by CJ-Wright** [comment]
This got sent to the wrong project :sheep:
