### ISSUE TITLE
bug in has r url

### ISSUE THREAD

**Issue by beckermr** [regro/cf-scripts#836]
This is a bug

```
2020-02-24 15:28:44,148 INFO     conda_forge_tick.auto_tick || /root/repo/cf-graph
2020-02-24 15:28:44,149 INFO     conda_forge_tick.auto_tick || VERSION IS MIGRATING networkit
~/repo/cf-graph/feedstocks/networkit-feedstock ~/repo/cf-graph
Your branch is up to date with 'origin/master'.
Already on 'master'
HEAD is now at 9d195f9 Merge pull request #1 from fabratu/master
HEAD is now at 70ef53a Merge pull request #3 from *********************/rebuild-python3801
error: pathspec '6.0.1' did not match any file(s) known to git
~/repo/cf-graph
2020-02-24 15:28:46,155 ERROR    conda_forge_tick.auto_tick || NON GITHUB ERROR
Traceback (most recent call last):
  File "/root/repo/cf-scripts/conda_forge_tick/auto_tick.py", line 688, in main
    hash_type=attrs.get("hash_type", "sha256"),
  File "/root/repo/cf-scripts/conda_forge_tick/auto_tick.py", line 147, in run
    migrate_return = migrator.migrate(recipe_dir, feedstock_ctx.attrs, **kwargs)
  File "/root/repo/cf-scripts/conda_forge_tick/migrators/version.py", line 410, in migrate
    r_url |= _has_r_url(cmeta.meta[src_key])
TypeError: unsupported operand type(s) for |=: 'bool' and 'NoneType'
```

**Comment by beckermr** [comment]
This is due to git urls
