### ISSUE TITLE
pip minimigrator erroring 

### ISSUE THREAD

**Issue by beckermr** [regro/cf-scripts#985]
We are seeing this

```ERROR conda_forge_tick.auto_tick:main(841): NON GITHUB ERROR
Traceback (most recent call last):
  File "/root/repo/cf-scripts/conda_forge_tick/auto_tick.py", line 798, in main
    hash_type=attrs.get("hash_type", "sha256"),
  File "/root/repo/cf-scripts/conda_forge_tick/auto_tick.py", line 169, in run
    migrator.run_pre_piggyback_migrations(recipe_dir, feedstock_ctx.attrs, **kwargs)
  File "/root/repo/cf-scripts/conda_forge_tick/migrators/core.py", line 233, in run_pre_piggyback_migrations
    if not mini_migrator.filter(attrs):
  File "/root/repo/cf-scripts/conda_forge_tick/migrators/use_pip.py", line 24, in filter
    return not bool(set(self.bad_install) & set(scripts))
TypeError: unhashable type: 'dict'```

CI run is here: https://app.circleci.com/pipelines/github/regro/circle_worker/1254/workflows/442616b2-b8cb-4dcf-ac46-182e6553aecf/jobs/16300

**Comment by beckermr** [comment]
cc @CJ-Wright
